### ISSUE TITLE
ЛАБ2

### ISSUE THREAD

**Issue by andreyTheGreatest** [Veetaha/numerical-methods-labs#1]
ГДЕ ЛАБ 2, ЛЕБОВСКИ????????

**Comment by Veetaha** [comment]
Its WIP, hope to finish it soon!

**Comment by akrava** [comment]
> Its WIP, hope to finish it soon!

We hope too!

**Comment by Veetaha** [comment]
@akrava PRs are welcome!

**Comment by Veetaha** [comment]
Since there has not been any activity under this issue lately, I'll close it
